site_name: Misay's Note
site_url: https://note.zt2misay2.cn

nav:
  - Home: index.md
  - Course:
      - Overview: course/index.md
      - 计算机组成原理: course/past/computation-structure.md
      - 数据库系统及安全: course/database/index.md
      - 人工智能: course/ai/index.md
      - 操作系统: course/os/index.md
  - Study:
      - Overview: study/index.md
      - 随笔: study/essays/index.md
  - Daily:
      - Overview: daily/index.md
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js
  - javascripts/sidebar.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - sane_lists
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
