site_name: Misay's Note
site_url: https://note.zt2misay2.cn

nav:
  - Home: index.md
  - Course:
      - Overview: course/index.md
      - 计算机组成原理: course/past/computation-structure.md
      - 数据库系统及安全: course/database/index.md
  - Study:
      - Overview: study/index.md
  - Daily:
      - Overview: daily/index.md
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections

extra_css:
  - stylesheets/extra.css
