name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [master] # 只在推送到master分支时触发
  pull_request:
    branches: [master]

permissions:
  contents: write # 允许工作流写入内容

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          # 如果有其他插件，在这里添加
          # pip install mkdocs-plugin1 mkdocs-plugin2

      - name: Build site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # 构建输出的目录
          publish_branch: gh-pages # 发布到gh-pages分支
          force_orphan: true # 强制使用孤立分支，清理历史提交
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
